[package]
authors = ["Praveen Perera <praveen@primcloud.com>"]
edition = "2018"
name = "moleculer-rs"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# serde
bytes = {version = "1.0", features = ["serde"]}
serde = {version = "1.0", features = ["derive"]}

# logging
log = {version = "0.4", features = ["serde"]}

# random
rand = "0.8"

# host info
hostname = "0.3"
